services:
  - type: web
    name: airefino-relay
    runtime: node
    repo: https://github.com/iayerza/AireFino
    branch: master
    buildCommand: npm install
    startCommand: node airefino-relay.js
    env: node
    plan: free
